# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import VerificaScore_pb2 as VerificaScore__pb2


class GreeterStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SearchScore = channel.unary_unary(
                '/verificaScore.Greeter/SearchScore',
                request_serializer=VerificaScore__pb2.ScoreRequest.SerializeToString,
                response_deserializer=VerificaScore__pb2.ScoreReply.FromString,
                )


class GreeterServicer(object):
    """The greeting service definition.
    """

    def SearchScore(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SearchScore': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchScore,
                    request_deserializer=VerificaScore__pb2.ScoreRequest.FromString,
                    response_serializer=VerificaScore__pb2.ScoreReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'verificaScore.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """The greeting service definition.
    """

    @staticmethod
    def SearchScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/verificaScore.Greeter/SearchScore',
            VerificaScore__pb2.ScoreRequest.SerializeToString,
            VerificaScore__pb2.ScoreReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
