# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VerificaScore.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VerificaScore.proto',
  package='verificaScore',
  syntax='proto3',
  serialized_options=b'B\022VerificaScoreProtoP\001\242\002\003HLW',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13VerificaScore.proto\x12\rverificaScore\"(\n\x0cScoreRequest\x12\x0b\n\x03\x63pf\x18\x01 \x01(\t\x12\x0b\n\x03mes\x18\x02 \x01(\t\"\x1b\n\nScoreReply\x12\r\n\x05score\x18\x01 \x01(\t2R\n\x07Greeter\x12G\n\x0bSearchScore\x12\x1b.verificaScore.ScoreRequest\x1a\x19.verificaScore.ScoreReply\"\x00\x42\x1c\x42\x12VerificaScoreProtoP\x01\xa2\x02\x03HLWb\x06proto3'
)




_SCOREREQUEST = _descriptor.Descriptor(
  name='ScoreRequest',
  full_name='verificaScore.ScoreRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cpf', full_name='verificaScore.ScoreRequest.cpf', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mes', full_name='verificaScore.ScoreRequest.mes', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=78,
)


_SCOREREPLY = _descriptor.Descriptor(
  name='ScoreReply',
  full_name='verificaScore.ScoreReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='verificaScore.ScoreReply.score', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=107,
)

DESCRIPTOR.message_types_by_name['ScoreRequest'] = _SCOREREQUEST
DESCRIPTOR.message_types_by_name['ScoreReply'] = _SCOREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScoreRequest = _reflection.GeneratedProtocolMessageType('ScoreRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCOREREQUEST,
  '__module__' : 'VerificaScore_pb2'
  # @@protoc_insertion_point(class_scope:verificaScore.ScoreRequest)
  })
_sym_db.RegisterMessage(ScoreRequest)

ScoreReply = _reflection.GeneratedProtocolMessageType('ScoreReply', (_message.Message,), {
  'DESCRIPTOR' : _SCOREREPLY,
  '__module__' : 'VerificaScore_pb2'
  # @@protoc_insertion_point(class_scope:verificaScore.ScoreReply)
  })
_sym_db.RegisterMessage(ScoreReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='verificaScore.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='SearchScore',
    full_name='verificaScore.Greeter.SearchScore',
    index=0,
    containing_service=None,
    input_type=_SCOREREQUEST,
    output_type=_SCOREREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
